cmd/run.go
- Pipe stdout, stderr, and stdin to os equivalents instead of only piping stdout
- Do not run command with bash. Instead run command directly. Running with bash will remove all colors or fancy terminal output that the user has setup in their shell
=> Run command pipe everything

cmd/run.go
=> Handle railway run with command that doesn't exist

.github/workflows/publish.yml
https://github.com/goreleaser/goreleaser-action/issues/233
=> GCC Multilib added to build

.github/workflows/build.yml, .github/workflows/publish.yml, .goreleaser.yml
* Now build on each PR
* Also cross compile OSX with CGO using clang
=> OSX Builds Cross + Build on PR

configs/main.go
* As a backstop for some instances of BigSur and VSCode terminals without $USER (InheritEnv turned off), catch the panic and recover via attempting to user $HOME
=> Homedir Backstop

cmd/init.go
* Account require for create, for now﻿
=> Require account for create

controller/up.go
* Instead of emitting the tarfile, send the bytes via multiform
=> Remove out.tar.gz

cmd/login.go, controller/user.go, go.mod, go.sum
Ask for user to hit enter before going to URL. Will update when #32 is merged to include open.
=> URL consent

cmd/env.go, cmd/init.go, cmd/list.go, cmd/login.go, cmd/status.go, cmd/up.go, cmd/version.go, cmd/whoami.go, controller/up.go, controller/user.go, errors/main.go, go.mod, ui/prompt.go, ui/spinner.go, ui/text.go
=> Visual improvements + clean up commands

cmd/status.go, configs/project.go, controller/user.go, errors/main.go, gateway/project.go
=> Cooler errors

cmd/login.go, controller/user.go
=> Less trains on login

errors/main.go
=> Login prompt

cmd/init.go
Error messages should prompt the user towards the correct actions﻿
=> Init has better error message

gateway/main.go
* Adds source for CLI header to tracking
=> Source header

controller/up.go, gateway/gitignore.go
* Original git ignore didn't actually guard against node_modules correctly. Replace the package with regex
=> Fix gitignore matching

install.sh, uninstall.sh
Shell script that can be installed via curl and sh. The user can use it like
```shell
sh -c "$(curl -sSL https://github.com/railwayapp/cli/blob/master/install.sh)"
```
The latest version will be used by default, but you can specify the `VERSION` environment variable to install a specific version of railway to install.
The install process is
- Create tmp directory
- Download latest asset from GH to tmp
- Compare checksums
- Extract asset
- Install to /usr/local/bin
- Remove tmp
There is also an uninstall script that remove `/usr/local/bin/railway`
=> Install and uninstall shell scripts

main.go
=> Fix flag parsing that shouldn't happen

configs/root.go
https://github.com/spf13/viper/issues/324
=> Dont use viper for unmarshal

cmd/run.go
Run with init
https://docs.docker.com/engine/reference/run/#specify-an-init-process
=> Run handle with Init

cmd/connect.go, main.go
- Builds commands for each plugin from project env
- Provides menu for selecting plugin to connect to
=> Add connect commands + selector

cmd/protect.go, controller/envs.go, entity/config.go, main.go, ui/prompt.go
Currently, no way to "unprotect" an environment other than editing config.json
=> Client-side Protected Environments

entity/project.go, gateway/project.go, ui/prompt.go
=> Show Teams in Link Command

controller/logs.go
Tiny fix from when I unwrapped that anonymous function
=> Fix log polling

controller/logs.go
* Wasn't really parsable before
Before:
After:
=> Clean Up Log Controller

controller/logs.go, entity/deployment.go, gateway/deployment.go, lib/gql/gql.go
This PR adds a mechanism to do fine grained GQL queries
It's a dependency for granular fetching as part of cooper/tail-up﻿
=> GQL Golang Queries

install.sh
* Modify the install script to support Raspberry Pi (armv6l)
=> Support Raspberry Pi Install

errors/main.go
railway init was recently separated into railway init & railway link, ProjectConfigNotFound error message updated to reflect this.
=> ProjectConfigNotFound error language updated.

cmd/run.go
Breaks arguments passed to railway run
=> Remove arg check for now

cmd/run.go
If PORT is provided by the envvars, use that for internal mapping﻿
=> Docker run uses provided PORT if available

cmd/panic.go, cmd/variables.go, controller/panic.go, main.go
Not pictured: running commands with -v will now show panicErr and stacktrace if it occurs
=> Variables Hint + Guard + Verbose Error Mode

controller/panic.go
=> Remove fmt print

controller/up.go
Handle passed error in filewalk﻿
=> Handle Passed Err

configs/main.go, controller/user.go, gateway/main.go
=> Support Staging Mode

configs/main.go
=> Write to staging config

cmd/environment.go, ui/prompt.go
=> environment command improvements

cmd/init.go, cmd/link.go, controller/project.go, gateway/project.go, go.mod, go.sum, uuid/main.go
Originally, users could only link projects by the project ID or by selecting their project from a list of projects. This PR adds an option to link projects using the project name.
Demo 👇
=> allow linking projects by name

controller/panic.go, controller/user.go, entity/panic.go
Sends CLI version to Telemetry Endpoint
=> Send Version with Panic

cmd/up.go, controller/up.go, entity/requests.go
This PR completes [RAIL-807](https://linear.app/railway/issue/RAIL-807/deployment-url-in-cli).
=> show deployment domain in up

cmd/completion.go, main.go
low hanging fruit for #113. Didn't add any dynamic completions.
=> non-dynamic shell completions

cmd/run.go
This PR adds support for environment flags on railway run
`railway run --environment=production <cmd>`﻿
=> Support Environment flag for run

controller/up.go
Supports directories with symlinks by literally just ignoring them﻿
=> Support Directories with Symlinks

.github/workflows/label-check.yml, controller/up.go
- Attempts to use the label upstream
Also created a PR upstream to pretty print into the [upstream action](https://github.com/jesusvasquez333/verify-pr-label-action/pull/31)
=> Attempt to use Label Upstream

cmd/status.go, cmd/up.go, controller/up.go, entity/project.go, entity/service.go, entity/up.go, gateway/project.go, gateway/up.go, ui/prompt.go
Initial work to get services supported in the CLI﻿
=> CLI Services Support

cmd/init.go, controller/envs.go, entity/project.go, go.mod, go.sum
Automatically import .env file on railway init﻿
=> Auto import .env file on init

package.json
https://github.com/railwayapp/cli/pull/182#issuecomment-1040931072
=> Added node engine warning

.gitignore, bin/railway.js, package-lock.json, package.json
Follow up to #182
This PR adds a static file inside bin that points to the binary to be downloaded by the host computer
=> Install binary correctly with NPM (again)

bin/railway.js
=> Silent Close

README.md
Yarn is confusing with this syntax
Update to the correct one﻿
=> Update yarn command

npm-install/postinstall.js, package-lock.json
=> fix npm install for windows

cmd/down.go, controller/down.go, entity/down.go, gateway/down.go, main.go
Closes #199
This PR will add a `railway down` command. I'm not comfortable enough with my GQL skills, reverse engineering skills, or Go skills to test it and be sure that I won't break anything important, so I have not tested anything.
=> Add `railway down`

cmd/run.go, cmd/up.go, cmd/variables.go, controller/envs.go, controller/project.go, entity/envs.go, errors/main.go, gateway/envs.go, main.go
A few changes to make working with multi-service projects easier
- `--service {serviceName}` flag support for up, run, and vars commands
- Prompt for service if necessary for run, vars, and var subcommands
=> Service support for up, run, and vars commands

README.md
=> Fix outdated curl installation url

README.md
- Fix railway cli docs url in `README.md`
=> Fix railway cli docs url in `README.md`

README.md
Force a re-publish of the CLI when merged
=> Force re-publish

ui/spinner.go
=> Only kill spinner if it's active

.goreleaser.yml, install.sh, npm-install/config.js, npm-install/postinstall.js, uninstall.sh
=> Add support for android

gateway/up.go
I had accidentally hardcoded a string here for purposes of taking a screenshot on #238
=> Fix error message

.github/workflows/homebrew.yml
When we get a new version auto publish to homebrew
=> Auto Publish to Homebrew

.github/workflows/publish.yml
Accidently had two lines with a dash
=> Accidental double dash

README.md
=> Just the Railway tap

cmd/down.go, main.go
=> feat: Bypass confirmation dialog `railway down`

controller/up.go
We were checking if the file was a directory before evaluating symlinks. This PR fixes that order to prevent treating linked directories as files.
=> Fix evaluation of symlinks on up

.github/workflows/ci.yml, .github/workflows/release.yml, install.sh
Renames the binary from `rlwy` to `railway`
=> fix release workflow

src/commands/service.rs, src/commands/up.rs
https://discord.com/channels/713503345364697088/1081435527812759624/1081435953991778314
=> fixes `railway service`

README.md, src/commands/shell.rs, src/commands/up.rs
=> Log `railway shell` and fix logs for `up`

README.md
- update readme to use bash
- add uninstall instructions
=> update readme to use bash

.cargo/config, .github/workflows/ci.yml, Cargo.lock, Cargo.toml, src/commands/add.rs, src/commands/delete.rs, src/commands/docs.rs, src/commands/init.rs, src/commands/login.rs, src/commands/service.rs, src/commands/unlink.rs, src/commands/up.rs, src/commands/variables.rs, src/subscription.rs, src/util/prompt.rs
=> Clean-up code

README.md
https://github.com/ScoopInstaller/Main/pull/4506 was merged so adding to the readme here
=> Add install instructions for Scoop

src/commands/run.rs
=> fix railway run when there are no services

src/commands/run.rs, src/commands/shell.rs, src/commands/variables.rs
=> Use constants in more places

src/commands/unlink.rs
=> fixes the unlink command

src/commands/run.rs, src/commands/service.rs, src/commands/shell.rs, src/commands/variables.rs, src/controllers/mod.rs, src/controllers/variables.rs, src/gql/queries/mod.rs, src/gql/queries/strings/VariablesForPlugin.graphql, src/gql/queries/strings/VariablesForServiceDeployment.graphql, src/gql/schema.graphql, src/main.rs, src/util/mod.rs
Fixes the variable rendering on these commands, before it was very hacky and didn't fully render the vars.
=> Render service variables for `railway variables`, `railway shell`, and `railway run`

src/commands/run.rs, src/config.rs
- Fixes a race condition that caused the config file to be overwritten
- Fixes `railway run`
=> fix config race condition

npm-install/config.js, npm-install/postinstall.js
=> fix npm install on windows

src/commands/run.rs
The environment argument was not being resolved, and was assumed to be an ID
=> fix `run` command environment arg resolution

.github/workflows/release.yml
=> fix generation of `.tar.gz` archives on windows

src/config.rs
=> Fix `railway up` in CI environments

Cargo.lock, Cargo.toml, src/commands/connect.rs, src/commands/mod.rs, src/commands/run.rs, src/consts.rs, src/controllers/variables.rs, src/gql/queries/strings/Project.graphql, src/gql/queries/strings/ProjectPlugins.graphql, src/main.rs, src/util/prompt.rs
Implement `railway connect` command from v2
Closes LOG-249
=> Connect command

package.json
=> update package.json files

.github/workflows/cargo-audit.yml, Cargo.toml, README.md
This pull request adds a new CI job to audit cargo for against a DB of known package vulnerabilities. It will run on a cron schedule and anytime cargo crates are updated or changed
=> Cargo Audit - CI

src/commands/shell.rs
=> early return in shell if no environment variables present

src/commands/shell.rs
=> fix<shell>: fixes shell responding to ctrl-c when it shouldn't

src/commands/up.rs
=> do not unwrap in up command

src/commands/logs.rs
Added a `deployment_id` option for logs. If omitted, logs will be pulled from the latest deployment like before.
Closes #398
=> Add deloyment id to logs

src/commands/shell.rs
From [this](https://discord.com/channels/713503345364697088/1138859969089908816) discord thread
=> Refactor to shell & inline comments for maintainence

.cargo/config, src/commands/connect.rs, src/commands/up.rs, src/controllers/project.rs, src/controllers/variables.rs, src/errors.rs, src/gql/queries/strings/Project.graphql, src/gql/schema.graphql
- Check service instance source and do naive matching to check database type so that we can support the `railway connect` command
- `railway connect {name}` now checks both plugin and service
- Fetch service instances when fetching project
=> Support `railway connect` for service databases

src/commands/link.rs
Instead of erroring, we simply don't prompt to link a service.
The code for the link command is a bit of a mess with a lot of duplication. Can clean it up at a later date.
=> support linking to services with no services

src/commands/connect.rs, src/controllers/project.rs
So you can `railway connect` with the migrated db
=> support `railway connect` for timescale image

.github/workflows/community.yml
adding a new GH Action so all community-made Issues and PRs get sent to the new buzz-oss discord channel
=> Create Community-Check GH Action

src/commands/up.rs
=> Revert "Remove .gitignore from ignore files in `up`"

src/commands/up.rs
Fast follow PR from https://github.com/railwayapp/cli/pull/477 to use `--ci` instead of `--cicd`
=> use --ci flag instead of --cicd

config.toml
Changes from another branch accidentally slipped into this one :(
=> Delete accidental config.toml

src/commands/service.rs
Fixes #507.
This makes sure the service command only displays services that are in the current environment.
=> Fix service command showing services that aren't in current environment

.github/workflows/ci.yml, .github/workflows/publish-npm.yml, .github/workflows/release.yml
Fixes #494
Also fixes the NPM version not being up to date
=> Fix release CI and NPM CI

src/commands/mod.rs, src/commands/redeploy.rs, src/gql/mutations/mod.rs, src/gql/mutations/strings/DeploymentRedeploy.graphql, src/gql/queries/strings/Project.graphql, src/main.rs
This command adds a `railway redeploy` command.
Fixes #298
=> `railway redeploy`

Cargo.lock, Cargo.toml, package.json
=> chore: Release railwayapp version 3.9.2

.gitignore, src/commands/deploy.rs, src/commands/mod.rs, src/gql/queries/mod.rs, src/gql/queries/strings/TemplateDetail.graphql, src/main.rs
=> Deploy template from CLI

src/commands/deploy.rs
=> prepend repo source with gh base url

src/commands/domain.rs, src/gql/queries/strings/Domains.graphql
- Fix check for whether or not a domain already exists
- Show all the domains that exist if there are any
- Properly format domains so they are clickable as URLs in the terminal
=> Improve output of domain command

src/commands/add.rs, src/commands/deploy.rs, src/commands/domain.rs, src/commands/environment.rs, src/commands/logs.rs, src/commands/open.rs, src/commands/redeploy.rs, src/commands/run.rs, src/commands/service.rs, src/commands/shell.rs, src/commands/status.rs, src/commands/up.rs, src/commands/variables.rs, src/commands/volume.rs, src/controllers/project.rs, src/errors.rs, src/gql/queries/strings/Project.graphql
If the project or environment has been deleted on Railway, we want to show a nicer error message.
=> better error messages when project or environment is deleted

src/commands/link.rs
Currently, after linking a project we don't give much feedback. This PR updates that to show the project that was linked and a few commands that you can run.
=> show next steps when linking a project

src/commands/add.rs, src/commands/deploy.rs, src/commands/down.rs, src/commands/variables.rs, src/controllers/variables.rs, src/gql/mutations/mod.rs, src/gql/mutations/strings/VariableCollectionUpsert.graphql, src/gql/queries/mod.rs, src/gql/schema.graphql
This allows you to set variables to a service. For example:
```
railway variables --set "HELLO=WORLD" --set "MULTIPLE=AT_ONCE"
```
=> Allow setting variables via `--set`

src/commands/login.rs
Fixes #553, which was caused by #545.
=> Fix login issue

.github/workflows/release.yml
- Create draft release and upload all the assets first
- Fix changelog generation
- Publish release when complete (I'm hoping this fixes the NPM publishing)
=> create draft release before publishing

src/commands/up.rs
=> Fix hanging of --ci option and watch patterns

Cargo.lock, Cargo.toml, src/commands/domain.rs, src/commands/environment.rs, src/commands/init.rs, src/commands/link.rs, src/util/prompt.rs
update deps to latest versions and some minor clippy fixes
=> update deps, clippy fixes

CONTRIBUTING.md, Cargo.toml, README.md, src/commands/docs.rs, src/config.rs
Update references of railway.app to .com
=> Point to railway.com

src/controllers/terminal.rs
some network devices might close the connection if it doesn't look like there's any traffic (despite this client and the server keeping the connection open). 
This ensures that doesn't happen by sending a websocket ping event every 10 seconds.
=> send a ping to ensure websocket connection does not close

src/commands/up.rs
=> fix bail import

src/main.rs
=> fix: Show update message only once per 24 hours

src/commands/connect.rs, src/controllers/database.rs
=> Revert "feat: Allow connecting to valkey and keydb when using 'connect' cmd"

src/commands/variables.rs, src/macros.rs
This fixes the handling of the `--json` flag.
Fixes #629
=> Fix the `--json` flag

src/commands/link.rs, src/gql/queries/strings/UserProjects.graphql, src/workspace.rs
You shouldn't be able to select projects that will be deleted with the `link` command.
=> filter deleted projects from link command

src/client.rs
=> bump gql client timeout to 30s

src/commands/ssh/mod.rs
This allows for the tmux sessions created in the ssh command to be named.
railway ssh --session => default name of railway
railway ssh --session testing => name of testing in the session
=> Named sessions

src/commands/login.rs, src/commands/whoami.rs
=> Support `--json` for the `whoami` command

CLAUDE.md, src/commands/add.rs, src/util/check_update.rs
Adds development guidance file for Claude Code to work effectively in this repository.
=> Add CLAUDE.md with development guidance

src/controllers/deployment.rs
retry streaming build logs for longer
=> longer log retry
