railwayapp/cli

cmd/build.go
configs/main.go
configs/project.go
configs/user.go
controller/envs.go
entity/envs.go
main.go

Lots of it taken from Suryas PR.
`railway build` command that dumps the env to .railway/env.json if the RAILWAY_PRODUCTION_TOKEN environment variable exists. We are not actually using the variable yet as a gql query needs to be built to handle it.

Build command

---

cmd/run.go
configs/main.go
errors/main.go
main.go

- Remove build command as it is no longer needed
- Rename RAILWAY_PRODUCTION_TOKEN to RAILWAY_TOKEN
- Handle calling railway run with no command

Remove build command, rename project token, and handle railway run with no command

---

.goreleaser.yml

Some terminals + some installs of Big Sur are shitting the bed and not passing in $USER
This should fix stuff for now

CGO_ENABLED=1

---

configs/main.go

* Until we have gco, user.Current is simply going to panic. I'm not sure why recover isn't working in that function, but this should be foolproof

Remove Home Entirely

---

cmd/init.go
errors/main.go
gateway/project.go

- Support railway init <projectID>
- Prompt for environment if there is more than 1 in a project
- Show "Project not found" error instead of "graphql: Not authorised" if fetching a project fails

Support railway init projectid

---

cmd/up.go
controller/up.go
entity/requests.go
gateway/main.go
gateway/up.go
go.mod
go.sum
main.go

Re-Enable up for Alpha

---

gateway/envs.go
gateway/main.go
gateway/project.go
gateway/up.go
gateway/user.go

* Up now uses token for authorization

Up Authorization

---

cmd/login.go
controller/user.go
gateway/user.go
main.go

Ability to login to Railway when the CLI cannot open a browser directly
See https://github.com/railwayapp/mono/pull/253 for an explanation of how this works

Browserless login

---

cmd/docs.go
constants/docs.go
controller/user.go
main.go

Adds a docs command to open up docs in the browser

Docs command

---

controller/user.go

- Use browserless login automatically if we detect we are in a codespaces environment
- Fix printf when falling back to browserless login

Browserless login in Codespaces

---

.gitignore
cmd/init.go
cmd/open.go
controller/project.go
gateway/project.go
ui/prompt.go

* When opening, pass the environment as a query strong so that it always sets your environment correctly﻿

Open to environment

---

gateway/up.go

* Simply let the request engine do its thing instead of trying to do multipart manually

Multipart without form breakage

---

cmd/init.go
configs/main.go
configs/project.go
configs/root.go
configs/user.go
entity/config.go
entity/project.go
entity/user.go

- Migrate local project ./railway config to user level ~/.railway config
- When looking for project config, find closest parent directory that has been init'd with a railway project
- When initing a new railway project, always use current working directory
The top level config has been split into user config and project config. The APIs for reading/writing user/project configs have stayed the same. But their implementations now call into the root config which deals with marsheling/unmarshelling the configs
The top level config will now look something like
```json
{
"user": {
"token": ""
},
"projects": {
"/users/jakerunzer/dev/railway-cli": {
"projectPath": "/users/jakerunzer/dev/railway-cli",
"project": "XXX",
"environment": "XXX"
},
"/users/jakerunzer/dev/railway-cli/node_modules": { …
```

Move cli configs into root dir

---

cmd/env.go

I know we don't want a utils folder, but min/max for ints should probably live somewhere else?

Use width of longest env var name when printing

---

controller/up.go

`node_modules` are the cause of a lot of failed deploys. For some reason pack does not recognize the project is a node if there is a `node_modules` directory.
This PR ignores it by default

Ignore node_modules by default

---

controller/version.go

If the version check code errors, we should bubble up that error before we deref

Guard against NPE on version check

---

install.sh

I'm running Ubuntu 20.04 and can't install via curl without `sudo` since `/usr/local/bin` is owned by root. These changes allow the user to specify an install directory (and binary name) optionally with environment variables. I also included a change to make the checksum test more compatible across different sh implementations. Bash/zsh implement `[[` but it's not in the sh spec. `[` is equivalent here.

Allow installation with custom binary name and install location

---

cmd/init.go
cmd/link.go
cmd/unlink.go
cmd/variables.go
cmd/version.go
configs/main.go
configs/project.go
main.go
ui/prompt.go

Changes:
- Renamed `disconnect` to `unlink` and split `init` into `init` and `link`
- Renamed `env` to `variables` to align verbiage with Dashboard
- Adjusted help text for all commands
- Both Stripe and Heroku CLIs were used as a style reference
Old renamed command still work but are deprecated.

Clean up global commands and help text

---

configs/main.go
configs/project.go

I had originally changed the config loading logic in #77 in order to have `ReadInConfig` return `viper.ConfigFileNotFoundError`. However, this broke things because `Config.configPath` would be unset if the project config didn't exist yet, breaking `railway run` (and possibly other commands).
This PR reverts back to the old way of loading configs with a fixed path and uses `os.IsNotExist()` to check the error instead

Revert config path handling and update DNE logic

---

cmd/init.go
cmd/link.go

This PR adds support for `railway link <project_id>` and keeps `railway init <project_id>` for legacy use (should remove later).

Support railway link <project_id>

---

cmd/link.go
entity/user.go
gateway/project.go

- Handle when there are no projects found
- remove avatar and projects from user entity
- display team projects in link command
It would be nice to eventually show which team the project is in when they are listed out. But for now, this PR just fixes the team projects not being selectable in the `railway link` project list.

Display team projects in link command

---

cmd/variables.go
controller/envs.go
entity/envs.go
gateway/envs.go

Before, the CLI was getting all plugin variables (pg, redis, etc), then pushing them all to the `env` plugin. This PR fixes this so that it only pulls vars from the `env` plugin.

Only get env variables when updating

---

cmd/connect.go
cmd/run.go
gateway/up.go

Noticed that `ctx` wasn't being used for a bunch of stuff, so fixed it.

Add use of context to a bunch of places

---

controller/logs.go

If we fetch the logs and nothing comes back, don't print an empty line﻿

Fix weird newline print

---

main.go

Variables is a bit long, so here's a `vars` alias to help out!
This also removes a duplicate definition of the `logs` command.

Add vars alias for variables command

---

cmd/run.go

Currently, if the command that `run` is running fails with an exit code, the actual railway run command returns with exit code 0. This isn't great and breaks things like CI.
Ideally we just capture the exit code of the sub command and exit with the same error. But it seems that this is not always the same cross platform.
See
- https://stackoverflow.com/questions/10385551/get-exit-code-go
- https://github.com/golang/go/issues/26539
In go 1.12 they released [ExitCode](https://golang.org/pkg/os/#ProcessState.ExitCode) on ProcessState, but I can not seem to get it to work locally on my Mac. Seems that is the case for others as well.
So as a comprimise, I try to use the exit code if it exists, otherwise I exit with exit code 1.

Run command exit code

---

install.sh

We had some arm64 alternative names in the install script, but missed adding the basic `arm64`
Fixes #104

Update install.sh to include arm64

---

cmd/run.go

In the event of a command failure, the ephemeral environment was being left aroudn

Clear ephemeral before teardown

---

cmd/connect.go
cmd/run.go

Previously we didn't show wtf we were doing for the docker build under the hood
Now, we show that such that the user doesn't sit there on this screen. Additionally, we can teardown the container if you hit CTRL + C on the log step now.

Show Dockerbuild + Handle Signal for teardown

---

configs/main.go
configs/project.go

I think I was able to fix the CLI not working on Windows. As windows doesn't really have a defined HOME directory, chose to use APPDATA/Roaming instead (lots of apps like Heroku CLI use this), ran a few tests with a example project and was able to get it working, short video walkthrough here:
https://www.loom.com/share/4ce6188c7406406a837a7710d70284d8
Let me know if there needs to be any changes or want a longer demo.
Thanks
UPDATE: updated to use `os.UserHomeDir`

Fix CLI on Windows

---

main.go

Just updates the help text for link

Help for link indicates you can specify projectId

---

cmd/run.go

We weren't checking for nil
Odd the linter didn't pick this up﻿

Fix NPE for logcheck

---

cmd/open.go
cmd/run.go
controller/project.go
entity/deployment.go
gateway/deployment.go
gateway/project.go
main.go

This PR closes [RAIL-826](https://linear.app/railway/issue/RAIL-826/expand-open-command-for-cli).
- `railway open` now opens your project dashboard.
- `railway open metrics` will open the metrics page. Aliased as `m`.
- `railway open settings` will open the settings page. Aliased as `s`.
- `railway open live` will open the deployed application. Aliased as `l`.
I've also left some questions in my self-review of the PR.

expand open command

---

controller/user.go
gateway/main.go
gateway/user.go

Associated Backboard PR https://github.com/railwayapp/mono/pull/1212
- Logout session in logout command and before logging in. This means that if you repeadedly login, you should only have a single user session (as opposed to a session for each login call)
- Send hostname with login request. The hostname will be used as the session name and appear on the /account/security page

Logout Session and Hostname

---

cmd/add.go
cmd/connect.go
cmd/protect.go
cmd/run.go
cmd/status.go
cmd/unlink.go
cmd/variables.go
configs/main.go
controller/config.go
controller/deployment.go
controller/deployment_trigger.go
controller/environment.go
controller/envs.go
controller/logs.go
controller/panic.go
controller/up.go
entity/project.go
errors/main.go
gateway/main.go
gateway/project.go

A lot of commands get the project and environment from the project config. This would fail if there was no project linked to the current directory. This PR lifts fetching of the project config to a controller which will use the project and environment for the project token if the RAILWAY_TOKEN is found.
Fixes #105

Use project/environment from project token if it exists

---

cmd/run.go

Upper-case project names were generating upper-case Docker tags, which aren't allowed by docker.
After this change:

Docker tags cannot contain upper-case letters, so lower-case them

---

cmd/run.go

The railway run command was looking for a project in the ~/.railway/config.json file and erroring if not found. This is a problem when running `railway run` in CI. This PR fixes it so the project config is fetched from the controller, which will use the project token if it exists.

Don't fail railway run if no project linked

---

ui/prompt.go

Because of the way we do templating here we override the default cursor behavior. Re-add it back manually.﻿

Fix Link Cursor

---

cmd/add.go
ui/prompt.go

This PR consolidates the prompt selection logic into two helper `selectString` and `selectCustom`.
- All selections now support filtering and show 10 items
- All selections now include a caret for the active item

Consolidate selection prompts into helper

---

cmd/environment.go

Prompted by #141 as I've seen users ask this before too.

add help text to environment command

---

cmd/variables.go
controller/config.go
controller/envs.go
entity/envs.go
gateway/envs.go

Use updated variable schema methods and stop using depreated methods
- allEnvsForEnvironment -> decryptedVariables
- updateEnvsForPlugin -> upsertVariablesFromObject, deleteVariable
Setting variables now upserts instead of setting all the envs for the entire plugin. Deleting variables is done one at a time.
We also no longer need a seperate query for fetching the envs with a project token.
Depends on https://github.com/railwayapp/mono/pull/1384

Use updated variable methods

---

entity/project.go
gateway/project.go
ui/prompt.go

Projects should now return in a more convenient order. 🔢

CLI Project Order by Last Updated 

---

README.md
cmd/delete.go
controller/project.go
entity/project.go
entity/user.go
gateway/project.go
gateway/user.go
main.go
ui/prompt.go

Added `railway delete` 
If you provide a project uuid, it will delete the project directly- if you don't it will allow you to browse your account's projects to delete.
Help appreciated on improving the copy on error/success.
Thanks to @TaroballzChen for spearheading this improvement, all I did was debugging.

Ability to Delete Project from CLI

---

.github/workflows/label-check.yml

Use the `pull_request_target` event so the action will work with forks.
Described here https://github.com/jesusvasquez333/verify-pr-label-action#note-when-working-with-forks

run the release label check for forks

---

.github/workflows/label-check.yml

So we don't end up with multiple actions run

Only use the pull-request-target event

---

npm-install/config.js
npm-install/postinstall.js
package-lock.json
package.json

I replaced `go-npm` with a script that downloads the binaries, untars it, and move them to `./bin` to then be capture by ["bin"](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#bin) (degit [uses this method](https://github.com/Rich-Harris/degit/blob/64b80577acf3313b669840f7452800ee8d09fbf3/package.json))
**Important note**: I don't know how to test it with `npm i -g @railway/cli`

Install binary correctly with NPM

---

.github/workflows/label-check.yml

To prevent the bot from commenting and flooding our Discord, just have the exit code returned vs commenting

Remove comment step and just fail CI

---

cmd/up.go
controller/up.go

Closes #181
This adds support for a .railwayignore file as suggested in #181. If this file is found in the current directory, the CLI will print out `Using ignore file .railwayignore` and use it in addition to `.gitignore` (using the same gitignore parser). If the file isn't found, then it will fall back to using `node_modules/` and `.git/` (the current functionality).

Add ignore file

---

cmd/up.go
main.go
ui/text.go

Closes #120 
This PR adds a `--verbose` flag to the CLI. Currently, only `up` uses it, but it could be used by other commands as well.
The output from #187 would probably be counted as verbose.
Example output:
```
❯ railway up --verbose
💁 Using verbose mode
💁 Loading project configuration
💁 Loading environment
💁 Using environment production
💁 Loading project
💁 Loading services
☁️ Build logs available at https://railway.app/...
==========================
Using Buildpacks!
==========================
...

Verbose mode for `railway up`

---

controller/up.go
go.mod
go.sum

Previously, we'd only consider top level ignore files (.gitignore,
.railwayignore), which led to some problems when doing `railway up`
in a monorepo environment.
For example,
```
mg@mbp operand % railway up
🚄 Laying tracks in the clouds... open web/node_modules/core-js-pure/actual/typed-array/reverse.js: too many open files
```
To fix this, we do a pre-scan to find all the relevant ignore
files in the project first, then apply them as necessary.
Some additional cleanup / fixes as well (e.g., closing files, etc).

controller/up: properly handle nested ignore files

---

cmd/shell.go
main.go

`railway shell` command that creates a subshell (using `$SHELL`) with the variables from environment/service loaded and available.
Thanks for the [suggestion wyzlle](https://canary.discord.com/channels/713503345364697088/943650028696768532/967033569203617833)

`railway shell` command

---

go.mod
ui/spinner.go
ui/text.go
ui/text_test.go
ui/tty.go

ANSI formatting codes are not always supported. For example, when piping to a file or when running in some CI environments. This PR checks on `init()` for a TTY and enables colors accordingly.
Tested with `railway up > output.txt` and `railway status > output.txt`

Disable colors if no TTY detected

---

controller/up.go

This PR fixes #224 by moving the ignore logic before the symlink check. This will ensure invalid+ignored symlinks won't break anything.

Move ignore check before symlink evaluation

---

cmd/up.go

Quick fix for deployment URL notification after `up`

Fix deployment live URL

---

cmd/up.go
controller/up.go
entity/up.go
gateway/main.go
gateway/up.go
main.go

This PR adds better looking error messages when GraphQL requests fail. It also has a special case for `up` deployments (since those aren't GraphQL).

Better looking errors

---

main.go

It looks like the description was copied from the --ephemeral flag.

Fix the description for the --service flag to run

---

install.sh

The example in the comments showed a command that would fail since it points to an HTML file. Changed this to the raw content URL.

Correct URL in comments example

---

README.md

I added the Railway CLI to [Nixpkgs](https://github.com/nixos/nixpkgs). [This package](https://search.nixos.org/packages?channel=22.05&show=railway&from=0&size=50&sort=relevance&type=packages&query=railway) recently hit the release-20.05 branch of NixOS. This PR adds installation instructions of the Railway CLI using Nix to the README file.

Add the Nixpkg to the README

---

cmd/up.go
controller/up.go
gateway/main.go
gateway/up.go

- Set railway cli version as header on up request
- Up from the project root instead of the current directory

Up from project root

---

configs/main.go
configs/project.go

- Remove legacy project migrate. This was needed from a very early version of the CLI.
- Do not toLower(cwd). This should fix https://github.com/railwayapp/cli/issues/246. I couldn't remember why we lowercased the directory in the first place. But after some initial testing, this seems to work fine.

Do not lowercase cwd

---

.github/workflows/publish.yml

Since we're using a repository_dispatch event, I think it's failing to detect the tag automatically
Manually set it to the new tag

Grab Tag from Client Payload

---

cmd/up.go
main.go

Fixes https://github.com/railwayapp/cli/issues/255
When up'ing using a project token, the project config path is empty. This PR will simply upload the current directory.

Fix up deploys with a project token

---

controller/up.go

We should be using the absolute path of the file so that prefix detection passes.
Fixes: https://github.com/railwayapp/cli/issues/259

fix gitignore file detection with up

---

cmd/variables.go
controller/deployment_trigger.go
controller/envs.go
controller/project.go
entity/deployment_trigger.go
gateway/deployment_trigger.go
gateway/project.go
main.go

This draft attempts to fix an outdated mutation to trigger a redeploy. I attempted to reuse the inferred `serviceID` and return it to the original callsite causing some changes here and there.
Unfortunately during local testing the mutation was successfully invoked but no redeployment was initiated server-side. I guess this is just filtered based on the headers disallowing CLI redeployments which may be intended for now or just a bug. The very same mutation fired from the UI by updating any variable does work though. As such this probably requires somebody to check that on your end.
Another observation I made is the type of mutation parameters. The server returns a 400 status code when the types are declared as `String!` instead of `ID!`. This is highly inconsistent with other queries and …

Fix outdated `deployEnvironmentTriggers` mutation

---

cmd/variables.go
controller/envs.go
entity/envs.go
gateway/envs.go
main.go

In this PR I have added an additional flag `replace` for `variables set` that replaces all variables of a service rather than just upserting them. This is helpful for automation using another single source of truth to push a snapshot of variables; otherwise, old variables have to be deleted one-by-before before setting the current ones.
I tried to reuse as much code as possible and thus renamed functions that were prefixed with `Upsert` in favor of `Update`. Additionally I have intentionally opted out of a short-hand form for the `--replace` flag to ensure nobody triggers it by accident.
Looking forward for feedback on this one.
Closes #264

Introduce optional replace semantics for `railway variables set` as an alternative to upsert

---

gateway/envs.go

`serviceId` is always required to fetch service variables, so update query accordingly. This will allow us to update the server-side nullability later.

Add String! to service variables query

---

cmd/link.go
configs/project.go
configs/root.go
errors/main.go
gateway/main.go

The CLI used to return the same generic error message if the user had never used the CLI before (missing root config) and when `link` had not yet been ran. Now, it returns useful errors in each case.
**railway login...**
&nbsp;
If a GQL request returned a "Not Authorized" response, you now get a friendly error instead of something unhelpful like "Failed to fetch projects".

Better error messages

---

cmd/link.go
cmd/unlink.go
cmd/up.go

If no project is linked on `railway up`, prompt the user to do so inline.
And fix panic for non-linked project during unlink
And shows a better error when linking with no projects

Prompt to link on up command

---

.github/workflows/release.yml
bin/railway.js
npm-install/config.js
npm-install/postinstall.js

Resolves #201 
Releases tarfiles for both Windows and Linux, so the NPM installer can fetch them.

release tarfiles for windows

---

src/commands/init.rs

Introduces the `--name` parameter for `init` command and allows setting the project name to skip the prompt.
```
Usage: railway init [OPTIONS]
Options:
-n, --name <NAME>  Project name
```

Allow setting the project name as a parameter of init command

---

.github/workflows/release.yml

Fixes https://github.com/railwayapp/cli/issues/316
[`3.0.5`](https://github.com/railwayapp/cli/releases/tag/v3.0.5) does **not** fix the aforementioned issue. As mentioned in the issue the error includes `npm ERR! https://github.com/railwayapp/cli/releases/download/v3.0.3/railway-v3.0.3-x86_64-pc-windows-gnu.tar.gz`. 
The error states that `railway-v3.0.3-x86_64-pc-windows-gnu.tar.gz` can't be fetched since the CLI does not provide a binary for `x86_64-pc-windows-gnu`.

release binary for `x86_64-pc-windows-gnu`

---

src/macros.rs

Using `tt` can lead to this being valid input for the macro:
```rs
commands_enum!(println!("a"));
```

don't use `$module:tt` in macros

---

src/commands/add.rs
src/commands/delete.rs
src/commands/docs.rs
src/commands/domain.rs
src/commands/login.rs
src/commands/open.rs
src/commands/service.rs
src/commands/up.rs
src/commands/variables.rs
src/macros.rs
src/util/prompt.rs

fix 409 errors on projects with mutiple services
fix non-interactive checks
usage
```bash
railway up --service <SERVICE_NAME> [PATH]
```
or
```bash
railway up --service <SERVICE_ID> [PATH]
```

allow user to select service on `up`

---

install.sh

This fixes the install script so it works in `dash`, the default `sh` on most Linux distros

make script compatible with `dash`

---

src/commands/login.rs
src/commands/up.rs
src/config.rs

- `railway up` now walks up to find the linked directory, and then deploys from there
- This also fixes a bug where absolute paths would fail to deploy
- `railway login` no longer errors when a user with no name logs in

Fix a couple of regressions

---

.github/workflows/release.yml

Fixes #347.
This is the same case as #316.

release binary for `i686-pc-windows-gnu`

---

Cargo.lock
Cargo.toml
src/commands/run.rs

This was causing issues where both the child and parent processes would exit at the same time, and the child process would be unable to respond to the SIGINT.
This PR ignores SIGINT on the parent process, and allows the child to handle it.
Resolves #384

Ignore CTRL+C on `railway run`

---

Cargo.lock
Cargo.toml

Currently, you have to `cargo install --locked`, and you get a warning about the yanked version. It seems like the only breaking change to v4 is upping the MSRV (still lower than what's declared for this project).

Update `open` off of yanked version

---

src/commands/run.rs

Exit the `railway run` process with the same exit code that the command being run exits with. This is important when using `railway run` to run tests and the tests exit with a non-zero exit code.

exit with the same exit code as process for railway run

---

src/config.rs

This fixes an issue where renaming a temporary file from system tmp folder to `~/.railway` could fail if, for example, they were on different OS partitions. This change writes the temporary file to `~/railway/config.tmp` instead, to ensure the operation is as safe as possible.

Write config tmp file in same directory

---

src/commands/down.rs
src/commands/mod.rs
src/commands/service.rs
src/gql/mutations/mod.rs
src/gql/mutations/strings/DeploymentRemove.graphql
src/macros.rs
src/main.rs

Partially brings back `railway down --yes` command (without the possibility to specify the environment—the linked one is used instead).
```
Remove the most recent deployment
Usage: railway down [OPTIONS]
Options:
-y, --yes      Skip confirmation dialog
```

Implement `down` subcommand

---

release.toml

When we run `cargo release patch|minor|major`, the version in `package.json` will automatically be updated

update the package.json version on `cargo release`

---

src/commands/up.rs

I've written some code that ignores .git and node_modules by default. I've also added a small amount of documentation to the block that handles the actual compression of the gzipped tarball, since it is, in my opinion, quite hard to read.

[command] [up] ignore .git and node_modules by default

---

Cargo.lock
Cargo.toml
src/commands/shell.rs

~~Uses [wmic](https://stackoverflow.com/questions/7486717/finding-parent-process-id-on-windows) and `std::process::id` to detect the parent process and therefore the correct shell to drop the user into.~~
Uses winapi syscalls and the `std::process::id` to detect the parent process of the cli. This either detects a shell listed below or defaults to `cmd`. Does nothing on non-windows platforms because of `#[cfg(target_os = "windows")]`
Supported shells:
- cmd
- Powershell 5
- Powershell 7 (pwsh)
- NuShell
- ElvSh
Edits:
- Because of brody, this now implements [this gist](https://gist.github.com/mattn/253013/d47b90159cf8ffa4d92448614b748aa1d235ebe4)

feat: windows specific shell detection

---

src/commands/run.rs

Fixes #386
Allows `railway run` to run other batch script windows programs, such as pnpm and npm.
- one match statement that sets the child proc and does all the argument handling
- moved command spawning away from the match statemnt
- handles no argument passed

fix<run>: allows `railway run` to run batch scripts on windows, including pnpm and npm.

---

src/commands/shell.rs

I left the dbg!() macro in by accident during the last pr. My bad

fix<shell>: remove dbg! macro in windows shell detection

---

src/commands/logs.rs
src/commands/up.rs
src/controllers/deployment.rs
src/controllers/mod.rs
src/gql/queries/mod.rs
src/gql/queries/strings/Deployment.graphql
src/gql/queries/strings/Deployments.graphql
src/gql/schema.graphql

This PR
- Streams both build and deploy logs when running the up command. This means that the logs will automatically show the correct output. I thought about switching the stream over, but was fighting too much with the Rust compiler and accessing the stream from multiple threads. Streaming both build and deploy logs should have low overhead so I don't think it is a problem.
- Stop streaming the logs and exit with error code 1 if the deployment fails
- Move deployment logs subscription fetching into controller functions
- New GQL query to fetch a single deployment
Fixes https://linear.app/railway/issue/PRO-506/railway-up-should-switch-to-tailing-application-logs-on-success

Stream both build and deploy logs for up command

---

src/commands/connect.rs

`railway connect` has the wrong description (likely copypaste error from `railway environment`).
```diff
- (fix/connect-desc ±) cli ツ railway --help
- Interact with Railway via CLI
- 
- Usage: railway [OPTIONS] <COMMAND>
- 
- Commands:
-   add          Add a new plugin to your project
-   completion   Generate completion script
-   connect      Change the active environment
+   connect      Connect to a plugin's shell (psql for Postgres, mongosh for MongoDB, etc.)
-   delete       Delete plugins from a project
```

fix(cmd): Describe `railway connect` properly

---

src/commands/connect.rs

Currently `railway connect Postgres` asks the user for the database password, this issue isn't present with the other database types when using `connect` as they either use a URI or have the password passed in as a flag.
This PR uses the `DATABASE_URL` variable as the only argument to `psql`
Specifying a connection string has been supported since [psql 9.2.0](https://www.postgresql.org/docs/release/9.2.0/#AEN114358:~:text=option%20for%20views-,Allow%20libpq%20connection%20strings%20to%20have%20the%20format%20of%20a%20URI,-Add%20a%20single)

use `DATABASE_URL` for psql

---

src/commands/run.rs
src/subscription.rs

This message that is printed after `railway run` often confuses people.

Remove confusing wording in `railway run`

---

src/commands/down.rs
src/commands/logs.rs
src/config.rs
src/gql/queries/strings/Deployments.graphql
src/subscription.rs

This fixes #436
This also fixes this for linked environments
This also makes sure it pulls from the latest *active* deployment, not just the latest deployment

Fix `railway logs` pulling from the wrong deployment

---

src/commands/shell.rs

Add silent flag to shell that removes "entering subshell with railway..." message

feat: add silent flag to shell

---

README.md

This is a simple update to the Homebrew installation section in this README. Seems like `rlwy` is outdated now.

fix: Update README Homebrew instructions

---

src/commands/link.rs
src/commands/logs.rs
src/errors.rs
src/gql/queries/strings/Projects.graphql
src/gql/queries/strings/UserProjects.graphql

This adds a new prompt in the `railway link` command allowing you to select a service.
Some notes:
- The links command internal code is a mess (and needs to be cleaned up)
- Logic is often being implemented 3x for the same thing
- This is the same with some other commands, but this is one of the worst

Allow service to be selected in `railway link`

---

src/commands/logs.rs
src/commands/run.rs
src/commands/up.rs

Previously, `up` and `logs` would pick a service if only one service was in the linked project. This often caused unwanted behaviour, so this PR changes it to a prompt.
Relevant thread: https://discord.com/channels/713503345364697088/1160376027365785711

Fix up from automatically selecting a service

---

src/commands/up.rs

This fixes a [silly bug](https://discord.com/channels/713503345364697088/1164669294966231171/1164705365003341854) where the terminal thinks it is TTY. Unfortunately, we can't do anything about that but we can add extra context to the error.

Add context if terminal is TTY

---

src/commands/shell.rs

Changes the description to make sure it is clear that it is a local subshell

Clarify `shell` command

---

src/commands/status.rs

Instead of showing all services, it now shows just the linked one.

Make `status` show linked service instead of all

---

src/commands/login.rs
src/config.rs
src/util/prompt.rs

If you answer no to the prompt about opening the browser, instead of just exiting, it'll now perform a browserless login instead.

Improve login

---

src/commands/up.rs

This removes the searching of .gitignore in the up command. This previously caused some unknown behaviour.

Remove .gitignore from ignore files in `up`

---

src/commands/up.rs

This pull request adds a new flag, --no-gitignore, to the up command. When this flag is used, the command will not ignore paths specified in the .gitignore file. This allows for more flexibility when deploying to different environments.
Superceeds #481

Add --no-gitignore flag to up command

---

Cargo.lock
Cargo.toml
package.json

👋 looks like the version is still pointing to the old release, correcting it to match with the latest release.
relates to https://github.com/Homebrew/homebrew-core/pull/168599

fix: update version to match with latest release

---

src/commands/up.rs

- Added new `up` command argument: `cicd`
When this argument is provided, cli won't stream deploy logs and will exit immediately after deploy status changes to `SUCCESS`.
This required changing `wait_for_failure` function to support this case. In both of them it will cause the cli to exit with either error exit code or zero, which would indicate success.

Support CICD

---

Cargo.lock
Cargo.toml
src/commands/link.rs
src/gql/queries/strings/Project.graphql
src/gql/queries/strings/Projects.graphql
src/gql/queries/strings/UserProjects.graphql
src/util/prompt.rs

Fixes #491
This also changes how the command works to be much simpler. Unfortunately, due to the graphql client we use giving us 3 types for a Project (which are all the same), a `NormalisedProject` struct is needed. Other then that, the code is much more self-explanatory.

Rewrite link command

---

src/commands/mod.rs
src/commands/volume.rs
src/errors.rs
src/gql/mutations/mod.rs
src/gql/mutations/strings/VolumeAttach.graphql
src/gql/mutations/strings/VolumeCreate.graphql
src/gql/mutations/strings/VolumeDelete.graphql
src/gql/mutations/strings/VolumeDetach.graphql
src/gql/mutations/strings/VolumeMountPathUpdate.graphql
src/gql/mutations/strings/VolumeNameUpdate.graphql
src/gql/queries/strings/Project.graphql
src/main.rs
src/util/prompt.rs

This PR adds the ability to update, list, create and delete volumes in a project.
A new command has been added, `railway volume` with various subcommands (create, delete, update, list, attach, detach).
Fixes #499

Add volume support to the CLI

---

Cargo.toml

This makes the binary size smaller in release mode

Optimise binary size

---

src/commands/up.rs

Enables debugging why `railway up` is failing.

verbose railway up flag

---

src/client.rs
src/commands/volume.rs

This makes the request timeout across the CLI to the GraphQL API 15 seconds.
This also adds a spinner when running `railway volume add`

Fix timeout & and add spinner

---

src/commands/up.rs

This pull request fixes a formatting issue in the `up.rs` file. The `Build failed` message was not being displayed correctly. This PR updates the message to display the correct error information and adds a fallback message if the error is empty.

Fix bad formatting

---

.gitignore
Cargo.lock
Cargo.toml
flake.nix
shell.nix
src/commands/login.rs
src/errors.rs

Updated rust version in nix shell.
Updated packages and fixed compilation error caused by breaking changes from hyper 1.0.0-rc, since cargo install doesn't respect cargo lock.
Added the SystemConfiguration framework on mac, since the linker was failing because of it in my machine.

Fix CLI compilation

---

README.md

A custom brew tap is no longer needed. https://formulae.brew.sh/formula/railway#default

Remove brew tap from instructions

---

src/commands/connect.rs
src/errors.rs

The default `DATABASE_URL` variable now points to the private network. This PR updates the connect command to first look for the public db url and connect with that if it exists.

Connect to public database URLs

---

Dockerfile

Fixes this whoopsie daisy:
TLDR: github artifacts reset file permissions and as someone who's used to gitlab I didn't even think of checking them. Whoops! Added a chmod command and now.. now it's done.

Fix exec permission in docker image

---

.github/workflows/release.yml

When a new release is complete, send a notification to #cli in the Railway Discord server

notify discord on release

---

README.md

This PR adds docker instructions to the readme for GitHub and GitLab based CI
(Description filled in by @JakeCooper)

Include docker instructions in readme

---

src/commands/shell.rs
src/commands/variables.rs
src/controllers/variables.rs
src/gql/queries/mod.rs

This PR updates several CLI commands to not fail if a service variable value is `null`. This can happen if the variable is a sealed variable.
The core change is that `get_service_variables` filters out variables with a `null` value and the remaining changes are replacing usages of the query that didn't re-use the function to re-use the function.
Note: Leaving as a draft until reviewed by someone else from the team that actually knows Rust. ^ _ ^

Handle null values in service variables

---

src/commands/login.rs
src/commands/whoami.rs
src/config.rs
src/errors.rs

If the `RAILWAY_API_TOKEN` is set, `railway login` doesn't really make sense. This PR shows the user that is already logged in.

handle `railway login` when api token is set

---

src/macros.rs
src/main.rs

Alias' can now be created like this:
```rs
commands_enum!(
actual_name(aliases, goes, here)
)
```

Add `railway env` as an alias for `railway environment`

---

src/commands/link.rs

This simple change adds something at the end of the link command showing that it was successful.

Add feedback after link

---

Cargo.lock
Cargo.toml
src/config.rs

This upgrades all dependencies to their latest version (except `async-tungstenite` due to `graphql_ws_client` not supporting the version of tungstenite that the latest version of `async-tungstenite` expects).

Upgrade dependencies

---

.github/workflows/release.yml

- Use gh cli for uploading built assets
- Remove homebrew tap updates because it wasn't doing anything and is not used

fix asset releases

---

src/commands/login.rs

This fixes a bug where if you have an invalid auth token, you will not be able to re login without running `railway logout` first. We only want to use the existing authenticated client if the `RAILWAY_API_TOKEN` variable is set.

only shortcircuit the login command if the RAILWAY_API_TOKEN is found

---

package.json
src/commands/add.rs
src/commands/docs.rs
src/commands/environment.rs
src/commands/login.rs
src/commands/open.rs
src/gql/mutations/mod.rs
src/gql/mutations/strings/ServiceCreate.graphql
src/gql/queries/mod.rs
src/gql/queries/strings/GitHubRepos.graphql
src/gql/schema.json
src/macros.rs
src/util/prompt.rs

This allows users to create services and databases in the linked project and environment, with similar options to the `+ Create` menu found within the project canvas.
Changes and improvements are outlined below.

Update `railway add`

---

src/commands/link.rs
src/util/prompt.rs

This allows you to press escape to skip providing a service when running railway link interactively.
Why: Sometimes people may want to link to a project for a monorepo without specifically selecting one service.

Make service optional when linking

---

src/macros.rs

This simple change allows aliases added to be displayed in the help text. Example:
```
environment  Change the active environment [aliases: env]
```

Display aliases in help text

---

install.sh

We currently get the latest version of the CLI for the install.sh script from looking at the `Cargo.toml` file in the repo. This is a problem since there is a brief period of time when the Cargo.toml file is updated to the newest version, but we haven't published a new release on GitHub yet. If you try to install during this time, it will fail. This PR instead gets the latest version from the GitHub releases which should always work.

get latest version from GitHub release

---

src/commands/open.rs

Previously, the open command wouldn't open to the correct environment. This PR fixes it by providing the `environmentId` query parameter.

Fix open command

---

Cargo.toml
src/commands/environment.rs
src/commands/mod.rs
src/errors.rs
src/gql/mutations/mod.rs
src/gql/mutations/strings/EnvironmentCreate.graphql
src/gql/mutations/strings/EnvironmentDelete.graphql
src/gql/queries/mod.rs
src/util/prompt.rs

This pull request adds 2 new commands:
- `railway environment new`
- `railway environment delete`
railway environment new is a command for creating new environments. It supports duplicating pre-existing environments, injecting variables for services that are being duplicated, and works fully in non-interactive mode (whilst also having an interactive mode).
This command allows you to delete environments. It will work in non interactive mode completely if you do not have 2FA on your account. If you do, then it won't, but this is the same case with any command that requires 2fa.

Add `railway environment new` and `railway environment delete`

---

src/controllers/variables.rs
src/gql/queries/mod.rs

Previously, if a service linked to had a sealed variable and you tried to use the variables or run command, it would exit with an error. This fixes it.

Fix sealed variables

---

src/commands/link.rs

If a service isn't provided in the command line flags and we aren't in a terminal, we will no longer prompt for it. This previously broke using it for stuff like CI when you don't want to link to a service.

Fix link command for non-terminal usage

---

.github/workflows/publish-docker.yml

Revert 'only run publish workflow on changes to the master branch'; Add manual job trigger.
60547529c3cdc817c9ba4ea9de63e195c8f205d1 Introduced a logic error which caused the workflow to never be triggered.
Please keep in mind that this workflow **IS NOT TRIGGERED BY GIT EVENTS** so setting any trigger rules/filters that mention branches, tags, commits etc would quite literally brick it.

Fix docker ci workflow

---

.github/workflows/publish-docker.yml

Since there was a problem with element order returned by GitHub's tags endpoint, this PR replaces that API request with a "tag" input field, which also makes possible to push any tag as the latest.

Fix manual docker ci tag

---

.github/workflows/publish-docker.yml

Ensure manually deployed tags don't contain a `v*` prefix

format manual docker deployment tag

---

Cargo.lock
Cargo.toml
src/commands/mod.rs
src/commands/ssh.rs
src/commands/up.rs
src/config.rs
src/controllers/mod.rs
src/controllers/service.rs
src/controllers/terminal.rs
src/main.rs

This adds a `railway ssh` command that creates a websocket connect to a relay server that will provide SSH capabilities to deployment instances.
`<project-name>` and `<service-name>` are required and deployment instance id is not because they are the minimum data required to find a deployment instance. `--deployment-instance` is only necessary if you have multiple replicas.
```sh
$ railway ssh --help
Connect to a service via SSH
Usage: railway ssh [OPTIONS]
Options:
-p, --project <PROJECT>
Project to connect to (defaults to linked project)
-s, --service <SERVICE>
Service to connect to (defaults to linked service)
-e, --environment <ENVIRONMENT>
Environment to connect to (defaults to linked environment)
-d, --deployment-instance <deployment-instance-id>
Deployment instance ID to connect to …
```

add `ssh` command

---

Cargo.toml
src/commands/check_updates.rs
src/commands/init.rs
src/commands/link.rs
src/commands/mod.rs
src/commands/run.rs
src/config.rs
src/macros.rs
src/main.rs
src/util/check_update.rs
src/util/compare_semver.rs
src/util/mod.rs

This PR adds automatic (daily) checks for new updates for the CLI, only in interactive mode. Alternatively, a user may manually check for updates using the `railway check-updates` command. 
Automatic daily checks run in interactive mode, in the background, for any command called. If a new version is detected, the CLI will push a message to the user (similar to NPM) that requests they update their CLI. 
Manual checks can be run as follows:
```bash
railway check-updates
```
This is what the check-updates command looks like when the version has changed:
This is what the check-updates command looks like when the version has not changed:
This is what the automatic check looks like when the check detects that the version has changed:
The data is grabbed (rather slowly) via the GitHub API …

feat: add check updates command

---

Cargo.lock
Cargo.toml
src/commands/init.rs
src/commands/link.rs
src/commands/list.rs
src/commands/ssh/common.rs
src/commands/ssh/mod.rs
src/commands/ssh/platform/unix.rs
src/commands/up.rs
src/config.rs
src/controllers/terminal/client.rs
src/controllers/terminal/connection.rs
src/controllers/terminal/mod.rs
src/errors.rs
src/gql/queries/strings/UserProjects.graphql
src/gql/schema.json
src/main.rs
src/workspace.rs

We are going away with the concept of a personal workspace. Right now personal workspaces in the CLI have both projects the user is a member of and projects owned by the workspace created for the user when they signed up.
And that workspace created for the user when they signup now has a team, so it appears twice in the selector.
To solve this we stop using `me.projects` and go throught he externalWorkspaces query, displaying each external project in its workspace.

Properly show external workspaces

---

src/commands/up.rs

Fixes #595 
It enables the users to provide the `--use-path-as-archive-prefix` flag if they want to upload a project subdir _while zipped with the subdir as archive root_. This maintains the old behavior for existing users that didn't provide the flag.
@brody192 let me know if I can improve the solution / code quality

Adds a flag for correct uploading of project subdirs

---

src/commands/up.rs

The ignore crate from ripgrep, by default, includes standard filters which automatically ignore files listed in .gitignore and other similar files. Simply not adding .gitignore manually through add_custom_ignore_filename has no practical effect, causing files listed in .gitignore to remain ignored.
This PR resolves this issue by explicitly disabling the git_ignore handler in the standard filters. This behavior has been tested locally to confirm that it correctly bypasses .gitignore.
See issue #608

fix: make –no-gitignore actually work

---

src/commands/connect.rs
src/controllers/database.rs

I normally use keydb or valkey. So therefore i made some changes that allows you to also connect with the **redis-cli** via the keydb or valkey public url.

feat: Allow connecting to valkey and keydb when using 'connect' cmd

---

src/commands/up.rs

We assume it's because the file is too large, but we don't know where the limit comes from and if that's the case. A middleware we use limits multipart field size for example. Logs this so we try to narrow the cause, so we can document the upload limit.
Related to: PRO-4145

Log 413 reason on up

---

src/commands/ssh/common.rs
src/commands/ssh/mod.rs
src/commands/ssh/platform/unix.rs
src/commands/ssh/platform/windows.rs
src/controllers/terminal/client.rs
src/controllers/terminal/connection.rs

The SSH logic has required more and more functionality that requires the client and server communicating when they are ready to send or receive data. This PR takes the welcome event handshake further by waiting for a response after starting a session or knowing that a command is being executed.
Today the client waits for a welcome after connecting before starting an interactive shell or sending a command to execute. The client doesn't know if the command is being executed or when data can start to be sent (such as key inputs or window size).
Now the client will get the `welcome` and after sending `init_shell` or `exec_command` the client will wait for `ready` if interactive shell or `stand_by` if waiting for a command to complete.

impl ready and stand by handshake for SSH

---

src/commands/add.rs
src/commands/check_updates.rs
src/commands/completion.rs
src/commands/connect.rs
src/commands/deploy.rs
src/commands/docs.rs
src/commands/domain.rs
src/commands/down.rs
src/commands/environment.rs
src/commands/init.rs
src/commands/link.rs
src/commands/list.rs
src/commands/login.rs
src/commands/logout.rs
src/commands/logs.rs
src/commands/open.rs
src/commands/redeploy.rs
src/commands/run.rs
src/commands/scale.rs
src/commands/service.rs
src/commands/shell.rs
src/commands/ssh/mod.rs
src/commands/starship.rs
src/commands/status.rs
src/commands/unlink.rs
src/commands/up.rs
src/commands/variables.rs
src/commands/volume.rs
src/commands/whoami.rs
src/macros.rs

The `--json` flag is currently global and can be added to all commands, but it is only actually used in a few. This PR moves the flag to the specific commands where it is used.

remove global json flag

---

src/commands/environment.rs
src/commands/variables.rs
src/gql/mutations/strings/VariableCollectionUpsert.graphql
src/gql/schema.json

^
Adds a `--skip-deploys` flag to the `railway variables` command.

allow skipping deploys when setting variables

---

Cargo.lock
Cargo.toml
README.md
src/commands/init.rs
src/errors.rs

Allows this command to create a project headlessly without any input prompts.
- Accepts a case-insensitive environment name or a case-insensitive UUID.
- Cleans up some very old code.

Add `--workspace` option to `railway init`

---

src/commands/environment.rs
src/gql/mutations/strings/EnvironmentCreate.graphql
src/gql/queries/mod.rs
src/gql/queries/strings/EnvironmentStagedChanges.graphql
src/gql/schema.json

Fixes timeout issues when duplicating environments that take longer than 30 seconds to process.
- Use background processing for environment duplication to avoid API timeouts
- Add polling mechanism to wait for duplication completion  
- Optimize retry timing with exponential backoff starting at 1s
- Provide seamless user experience with unified spinner messaging

Fix environment duplication timeout when process takes longer than 30s

---

.github/workflows/ci.yml
shell.nix
src/commands/logs.rs
src/commands/up.rs
src/controllers/deployment.rs
src/gql/queries/strings/BuildLogs.graphql
src/gql/queries/strings/DeploymentLogs.graphql
src/gql/subscriptions/strings/BuildLogs.graphql
src/util/logs.rs

I've felt a couple pains when using the CLI's log command during local dev:
- `logs` CLI command isn't terribly Claude Code friendly b/c it streams by default
- I can't use filters, e.g. just get the error logs from build
- I can't grab X logs
- `src/util/logs.rs` - common trait + formatters for logs
- update gql calls to add queries + request attributes everywhere
- add queries in `src/controllers/deployment.rs`
- `src/commands/logs.rs` - add `--filter`, `--limit` options
- `nix-shell --run "cargo run -- login"`
- `nix-shell --run "cargo run -- link"`
- `nix-shell --run "cargo run -- logs"` streams deploy + should match current version of railway CLI output
- `nix-shell --run "cargo run -- logs --build"` same thing for build logs
- `nix-shell --run "cargo run -- logs -n 1"` doesn't …

Add `--lines` / `-n` and `-f` / `--filter` options to log command

---

src/commands/logs.rs

If you try to lookup logs for a failed deployment, the CLI won't let you:
If you only have failed deploys, the CLI says there are no deployments:
- refactor the fetching logic so that we a) still have the "fallback to successful" logic, but b) we allow you to pass in whatever ID you want
- `railway logs some-made-up-id` => should error w/ a 404
- `railway logs some-real-failed-id` => should work
- `railway logs ` when you only have a failed deploy => should work
- `railway logs` when you only have a success + a failed deploy => should work and give you the success logs

Fix for `railway logs`: allow using deployment ID to look up failed build logs

---

src/commands/deployment.rs
src/commands/down.rs
src/commands/logs.rs
src/commands/mod.rs
src/gql/queries/strings/Deployments.graphql
src/main.rs

When trying to use the CLI to debug broken builds, the flow requires you to leave the CLI and head to the web app b/c we don't expose a good way for you to find failing builds. This would be nice for LLMs to be able to do to close the loop for users too.
This PR adds `railway deployment` command with subcommands `up`, `redeploy` and `list`
- extend `src/gql/queries/strings/Deployments.graphql` to have a `first` arg + query the meta. Update existing callsites to pass None for first
- main changes in `src/commands/deployment.rs`
- add `deployment` command
- alias `up` + `redeploy` as subcommands
- add a `list` command
- `railway --help` should describe the new command in a line
- `railway deployment --help` should describe display descriptions of all commands
- `railway deployment  up …

Add `deployment` command with subcommands for list, up and redeploy

---

Cargo.lock
Cargo.toml
src/macros.rs

Addresses [`RUSTSEC-2024-0436`](https://rustsec.org/advisories/RUSTSEC-2024-0436.html). Replaces the unmaintained `paste` crate with the `pastey` crate.
Fixes https://github.com/railwayapp/cli/issues/599

Replace no longer maintained `paste` crate
